# Configs for running the pipeline, saved as default 

# name of the project and run you are working on
project_name: proj_name
run_name: run_name

# full path to the imput directory where your files to be processed live
input_dir: C:/input/path

# type of file to process, .D or .mzML
iput_type: .D

# thesholds/analysis parameters
rt_threshold: 0.025                 # max time (seconds) from the supplied rt a peak can be or peak is flagged
endpoint_threshold: 10              # max difference between endpoint heights (as a percent of max height of peak) for peak to be flagged
variance_threshold: 1e-6            # minimum variance to be included in PCA plot
width_threshold: 25                 # maximum width of a peak before it is flagged as overloaded
pca_var: 0.8                        # decimal percent of how much variance accounted for by plotted pca, 0.8 means plot all pcs that in sum account for 80% of variance